name: Deploy static site to GitHub Pages (with PAT)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to gh-pages with PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_branch: gh-pages
          publish_dir: ./site
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          commit_message: "deploy: ${{ github.sha }}"
